MPESA_CONSUMER_KEY: '6GqByyURNGKnFtmbgDHEHDPEWZ1HtyjT'
MPESA_CONSUMER_SECRET: 'AZR4sx5xlcCh683t'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORT_CODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMjMwODExMTAwMDI3'
CALLBACK_URL: 'https://a3e7-154-70-24-1.ngrok-free.app/'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"